build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    CONTAINER_IMAGE_REPO: $N49REGISTRY/pytexcv/pytexcv
    CONTAINER_IMAGE_RELEASE: $CONTAINER_IMAGE_REPO:latest
    CONTAINER_IMAGE_COMMIT: $N49REGISTRY/pytexcv/pytexcv:build-$CI_COMMIT_TAG
  script:
    - echo "{\"auths\":{\"$N49REGISTRY\":{\"username\":\"$N49REGISTRY_USER\",\"password\":\"$N49REGISTRY_PW\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/Dockerfile
        --destination $CONTAINER_IMAGE_RELEASE
        $(if [ "$CI_COMMIT_BRANCH" = "master" ]; then echo '--destination $CONTAINER_IMAGE_COMMIT' ; fi)

